### POST MAQUINARIA
POST http://localhost:3000/machines HTTP/1.1
content-type: application/json

{
    "name": "amasadora 1",
    "description": "amasadora de 10kg",
    "purcharse_date": "2021-01-01",
    "desired_maintenance": 3,
    "user_id": "6659d6c240e489a6515d6396"
}
### GET ALL MAQUINARIA
GET http://localhost:3000/machines HTTP/1.1
### GET POR ID MAQUINARIA
GET http://localhost:3000/machines/6681d8ec3ba45a93828f4670 HTTP/1.1
### PUT MAQUINARIA
PATCH http://localhost:3000/machines/6681d8ec3ba45a93828f4670 HTTP/1.1
content-type: application/json

{
    "name": "amasadora 2"
}
### DELETE MAQUINARIA
DELETE http://localhost:3000/machines/6681d8ec3ba45a93828f4670 HTTP/1.1