### POST RECETA
POST http://localhost:3000/recipes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDRAYXNkLmNvbSIsInN1YiI6IjY2OGNiYTYxODY5ZTRmNTIzYTQzYmU4ZiIsImlhdCI6MTcyMTc5OTA2MSwiZXhwIjoxNzIxODI5MDYxfQ.ivInTj9TPKB6trLrdjec5dBWsN20cw49ANu1ljTT7JI

{
    "name": "Tarta",
    "ingredients": "Queso, huevos, azúcar",
    "steps": "Mezclar los ingredientes y hornear",
    "author": "Jose",
    "recommendations": "No comer en exceso",
    "standardUnits": 3,
    "supplies": ["6682e1ffbc32d9f674079daf"]
}

### GET RECETAS
GET http://localhost:3000/recipes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDRAYXNkLmNvbSIsInN1YiI6IjY2OGNiYTYxODY5ZTRmNTIzYTQzYmU4ZiIsImlhdCI6MTcyMTc5OTA2MSwiZXhwIjoxNzIxODI5MDYxfQ.ivInTj9TPKB6trLrdjec5dBWsN20cw49ANu1ljTT7JI

### GET RECETA POR ID
GET http://localhost:3000/recipes/66a092489f869bc72745a170 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDRAYXNkLmNvbSIsInN1YiI6IjY2OGNiYTYxODY5ZTRmNTIzYTQzYmU4ZiIsImlhdCI6MTcyMTc5OTA2MSwiZXhwIjoxNzIxODI5MDYxfQ.ivInTj9TPKB6trLrdjec5dBWsN20cw49ANu1ljTT7JI

### GET RECETA POR AUTOR
GET http://localhost:3000/recipes?author=Jose HTTP/1.1

### PUT RECETA
PATCH  http://localhost:3000/recipes/6663743dd6f6cd3e426fc8eb HTTP/1.1
content-type: application/json

{
    "standardUnits": "4"
}

### DELETE RECETA
DELETE  http://localhost:3000/recipes/6663743dd6f6cd3e426fc8eb HTTP/1.1
content-type: application/json

{
    "standardUnits": "4"
}