### LOGEARSE
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "asd2@asd.com",
    "password": "123456"
}
### REGISTRARSE
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "asd2@asd.com",
    "password": "123456"
}
### PRUEBA AUTH
GET http://localhost:3000/auth/profile
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDJAYXNkLmNvbSIsInN1YiI6IjY2ODZkZmQ3NTc3YjZiOWQ1MjM4NjY3YyIsImlhdCI6MTcyMDExNTM0NiwiZXhwIjoxNzIwMTE1NjQ2fQ.imPPYCj-FsGj2kFt0X_0E38FLH8W17lyofIjL1UDL2g
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZDJAYXNkLmNvbSIsInN1YiI6IjY2ODZkZmQ3NTc3YjZiOWQ1MjM4NjY3YyIsImlhdCI6MTcyMDEyMDkyOCwiZXhwIjoxNzIwMTIxMjI4fQ.BB-gnYahSPtMDCTHVtXWp3yJ9dzmtlIBkkBwk4bVgic